"""empty message

Revision ID: 2c0c874a7f90
Revises: 36b5398bef7f
Create Date: 2023-06-27 17:33:50.880951

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '2c0c874a7f90'
down_revision = '36b5398bef7f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('Pictures',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('user_id', sa.String(), nullable=True),
    sa.Column('username', sa.String(), nullable=True),
    sa.Column('title', sa.String(), nullable=True),
    sa.Column('comments', sa.Text(), nullable=True),
    sa.Column('image_path', sa.String(), nullable=True),
    sa.Column('create_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('Pictures', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_Pictures_username'), ['username'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('Pictures', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_Pictures_username'))

    op.drop_table('Pictures')
    # ### end Alembic commands ###
